package com.example.demoaws.modal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "employee")
public class Employee {
  @DynamoDBHashKey(attributeName = "employee_id")
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  private String firstName;

  @DynamoDBAttribute
  private String lastName;

  @DynamoDBAttribute
  private String email;

  @DynamoDBAttribute
  private String phone;

  @DynamoDBAttribute
  private Department department;
}
